@Library('c3i') _

def artifactoryID = "ArtifactoryConan"
def artifactoryCredentials = "c3i_on_artifactory"
def artifactoryURL = "https://conan.jfrog.io/conan"

def user
def password


withCredentials([usernamePassword(credentialsId: artifactoryCredentials,
                                  usernameVariable: 'ARTI_USER',
                                  passwordVariable: 'ARTI_PASS')]) {
    user = env.ARTI_USER
    password = env.ARTI_PASS
}

c3iManager.runBuild(this, artifactoryURL, user, password, artifactoryID)


