@Library('c3i') _


withCredentials([usernamePassword(credentialsId: artifactoryCredentialName, usernameVariable: 'ARTIUSER', passwordVariable: 'ARTIPASS')]) {
    c3i.runBuild(this, env.ARTIURL, env.ARTIUSER, env.ARTIPASS)
}


