def arti_instance = "https://conan.jfrog.io/conan"
def credential = "ArtifactoryConan"
def artifactory_name = "ArtifactoryConan"
def core_repo = "https://github.com/lasote/c3i_core.git"

def win_tmp_path = "C:/kk"
def json_file_path = 'c3i_configs.json'
def the_json
def repo_name

def PipInstall(p){
    command = "pip install ${p} --upgrade"
    if(oss == "Windows"){
      bat script: command
    }
    else{
      sh script: command
    }
}

def Process(oss, build_folder, commit, url, profile, ref){
    PipInstall("virtualenv")
    withPythonEnv('python'){
         PipInstall("conan")
         dir(build_folder){
           checkout([$class: 'GitSCM', branches: [[name: commit ]], userRemoteConfigs: [[url: url]]])
           writeFile file: "_profile.txt", text: profile
           def server = Artifactory.newServer url: arti_instance, credentialsId: credential
           def client = Artifactory.newConanClient(userHome: build_folder)
           def remoteName = client.remote.add server: server, repo: repo_name
           client.run(command: "create . ${ref}  -pr _profile.txt".toString())
           client.run(command: "remote list")
           def b = client.run(command: "upload ${ref} -r '${remoteName}' --all -c".toString())
           server.publishBuildInfo b
         }
    }
}

node("Linux"){
  stage("Generate builds"){
    def basedir = pwd()
    checkout scm
    dir(".c3_core") {
      git branch: 'master', url: core_repo
      sh(script: "./c3i/master/launch.sh ${basedir} ${json_file_path}")
      the_json = readJSON file: json_file_path
    }
  }
  stage("Create Build Artifactory repo"){
    def server = Artifactory.server artifactory_name
    repo_name = "c3i_build_pr_${env.BUILD_NUMBER}".toString()
    def config = "{ \"key\": \"${repo_name}\", \"rclass\": \"local\", \"packageType\": \"conan\"}"
    // TODO: Get url from arti server?
    def url = "${arti_instance}/api/repositories/${repo_name}"
    def response = httpRequest url:url, \
                               httpMode: "PUT", \
                               requestBody: config, \
                               authentication: credential, \
    						   customHeaders: [[name: "content-type", value: "application/json"]]
  }
}


the_json["groups"].eachWithIndex { group, gix ->
  def builders = [:]
  group.eachWithIndex { conf, cdx ->
    def oss = conf["oss"]
    builders["${oss} - Stage ${gix} - Build ${cdx}"] = {
      node(oss) {
        stage("${oss} - Stage ${gix} - Build ${cdx}"){
          def commit = conf["commit"].toString()
          def ref = conf["ref"].toString()
          def profile = conf["txt"].toString()
          def url = conf["url"].toString()

          echo ref
          echo profile

          def curdir = pwd().toString()
          def build_folder = "${curdir}/package_repo".toString()
          if(oss == "Windows"){
            build_folder = win_tmp_path + "/${env.BUILD_NUMBER}_${gix}_${cdx}"
          }

          if(conf["docker_image"]){
              def image = conf["docker_image"]
              sh "docker pull $image"
              docker.image(image).inside("-e CONAN_USER_HOME=${curdir}") {
                  Process(oss, build_folder, commit, url, profile, ref)
              }
          }
          else{
                Process(oss, build_folder, commit, url, profile, ref)
          }
        }
      }
    }
  }

  parallel builders
}

